logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
server:
  port: 8090
base-url: http://localhost:${server.port} 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   
keycloak-client:
  server-url: http://172.26.1.241:8080
  realm:  laolis
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: api-gateway
            client-secret: T0ebYlXLcsP38hfQwgDXimCXswDvnujE
            authorization-grant-type: authorization_code
            redirect-uri: ${base-url}/login/oauth2/code/keycloak
            scope: openid
        provider:
          keycloak:
            authorization-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
            user-name-attribute: name
            user-info-authentication-method: header
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
          issuer-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}
  cloud:
    gateway: 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
            - PATCH
            - OPTIONS
            add-to-simple-url-handler-mapping: true
      routes:
        - id: datamodel
          uri: lb://datamodel
          predicates:
            - Path=/datamodel-api/**
            - Method=GET,POST,DELETE,PUT,PATCH,OPTIONS
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
